### PR TITLE
Adding encryption feature to the implementation

### PR DESCRIPTION
**Pull request by muhammadsalah**
I am not so good with mongoose, however, I tried to put some code that encrypts the credentials in case mongodb is compromised.
I was about developing the same interface you have, and I found out about yours now, so I put mine aside, and I implemented this extra feature.
The code runs through npm test successfully, however, I did not add any test cases.
I will appreciate any feed back from you.
Thank you.

### CODE REVIEW

**Comment by muhammadsalah** [comment]
The code doesn't break any of the tests, and I tested it on my pc.
However, it's not functional.
Somehow, I can't go inside pre save or pre find.
But I think you got the idea, please can you advice on how to do that?

**Comment by muhammadsalah** [comment]
The code is not in a good shape now, so please just fill me in if I am trying to do it in the right way.
Thank you.
I will leave it as is now.

**Comment by muhammadsalah** [comment]
A better approach I think, is to have the encryption on another level, that interfaces with all the components.
So I think I will quit trying to implement it on this level.

**Comment by PPCM** [comment]
@muhammadsalah  thanks for your works, I will take a look and send you a feed back

**Pull request closed without merging**
